### ISSUE TITLE
Restart at certain point in the game

### ISSUE THREAD

**Issue by willwade** [AceCentre/morse-learn#10]
I'm not convinced its not storing where you've got to each time reliably. So have a way of telling the app to start at a different letter.

Ref:#3

**Comment by gavinhenderson** [comment]
Bug that needs some investigation

**Comment by gavinhenderson** [comment]
@willwade I can't seem to replicate this bug, it remembers where I was and then gives me words with the letter

Going to close this but if you can replicate it then ill reopen

**Comment by willwade** [comment]
Thanks for investigating!
