### ISSUE TITLE
Create a way of playing on a mobile with no keyboard attached

### ISSUE THREAD

**Issue by willwade** [AceCentre/morse-learn#15]
- Go to https://morse.withgoogle.com/learn/
- Click the "Play demo  on desktop"
- You get a screen like this

<img width="1152" alt="Screenshot 2020-05-26 at 20 09 11" src="https://user-images.githubusercontent.com/229352/82940464-c9512e80-9f8c-11ea-8c48-dfed8acb0f7a.png">

**What we want**

Provide part of the start splash screen - an option that says "Either use a hardware keyboard or switches sending dot and dash - or use the demo on-screen keyboard here"

Tapping on that brings up a screen like the shown. So it will capture those keys as well as hardware keyboard. 

**Question??** 

Where on earth is this code in our repo?? It's taken from Googles morse-learn so not sure where it's gone!

**Comment by gavinhenderson** [comment]
Currently working on this.

My plan is to show this overlay no matter what, even if you have a hardware keyboard plugged in.

I think (as you mentioned will) this code isn't in their repo, so ill pull it from the website but it will take some work
