### ISSUE TITLE
Bug: Highlighting wrong key

### ISSUE THREAD

**Issue by willwade** [AceCentre/morse-learn#16]
I think we've introduced a bug somewhere along the line..

See this video:

https://www.dropbox.com/s/8n0gaqaoanif7o1/Screen%20Recording%202020-05-26%20at%2020.16.17.mov?dl=0

Compare with https://morse.withgoogle.com/learn/ - where the current letter is given that little highlight animation. Ours seems to be off.

**Comment by sylvansson** [comment]
I noticed this too. I don't think it was introduced in my last PR, but I'll do a `git bisect` to figure out what happened. Can you assign it to me?

**Comment by willwade** [comment]
Yeah. I wasn’t sure when it happened. Sorry if that sounded like I was blaming you!  Poor QA testing by me for sure.

**Comment by sylvansson** [comment]
We currently highlight a letter _after_ sliding to the next one, so it looks like we highlight the wrong one. I think we introduced the timing issue in 3bb73487acb94964914be727a2d817e57ac80bbe. I'll see if I can get the animation to be more in sync with the "Correct!" sound.

**Comment by gavinhenderson** [comment]
Fixed in #19
