### ISSUE TITLE
Build a configuration screen - access, sound/audio, restart from

### ISSUE THREAD

**Issue by willwade** [AceCentre/morse-learn#3]
Build in a configuration screen to configure: one, two or three keys (switches)
(ref: https://github.com/googlecreativelab/morse-learn/issues/11, https://github.com/googlecreativelab/morse-learn/issues/7, https://github.com/googlecreativelab/morse-learn/issues/3) (note: user to choose which keys are used for morse-learn), ability to load your own sounds or images

Ref: https://raw.githubusercontent.com/AceCentre/MorseWriter/master/screenshot2.png

**Comment by gavinhenderson** [comment]
More context

* Build some kind of key mapping page
* Set timings of gaps, dots, dashes etc

**Comment by gavinhenderson** [comment]
@willwade Some questions.

For sound and audio, is the new settings menu clear enough to cover that requirement?

![Screenshot 2021-04-13 at 16 52 02](https://user-images.githubusercontent.com/1359202/114582533-941eff00-9c78-11eb-9ed0-d289dd4db874.png)

> restart from

Currently it restarts from where you left off, is that not enough? You can also restart by clicking the alphabet at the top? In what scenario would someone want to begin from somewhere thats not the beginning or where they left off? Maybe we need to make the restart option more obvious?

So access, right now we only support 'two keys' mode. We want to support one and three key? Makes sense. One key being hold the key for dash and tap for dot? For three key you have a dot, dash and next letter?

Whats more important one or three key? Ill make separate issues for adding each 'mode'. Although they will require a fair amount of work, mainly figuring out how they will work

**Comment by willwade** [comment]
One key more important than 3 key for sure. And in one key a dash is 3x one dot length. 

And sure. Maybe no real need for the restart thing - not now it's confirmed it's remembering where you part where. Hmm. Make it more obvious maybe. As you say not sure how we do that.

**Comment by gavinhenderson** [comment]
Closing this issue as I have everything covered elsewhere

One switch issue: https://github.com/AceCentre/morse-learn/issues/21
Checklist item for restart button: https://github.com/AceCentre/morse-learn/pull/19
