### ISSUE TITLE
Report tool 

### ISSUE THREAD

**Issue by willwade** [AceCentre/morse-learn#4]
Create a report tool: A table and exportable csv of each letter, how many times they got it wrong, right, average time to write each letter, and number of times practiced (a bit like the output we have created in https://github.com/willwade/reaction-test-01). 

This is useful as we would like to see how long it takes people to learn the entire alphabet in different modes (Audio only, Audio+Visual, Visual only for example). This might also solve the Word Per Minute problem (See https://github.com/googlecreativelab/morse-learn/issues/12)

Maybe accessed from #3 ?

**Comment by willwade** [comment]
Thinking further about this. We'd love to put this app out there to crowd source research how long it takes to lean morse and then how quickly you can type using it. 

So I think to meet this we would need to 
- allow for local caching of where you are up to 
- at some point, submit data. Ontop of raw data we would like to know some data like age bracket, native language, location (country), used morse before and whether interested to be involved in future research with us. If they do ask for email address
- we would also need to give user a option of learning via auditory or visual cues. Ideally we want a 50/50 split. The suggestion is to suggest one depending on how many we need to agree to do it. 

Lastly. We don't have a way of testing writing speed.  That's an issue in itself that needs doing.

**Comment by gavinhenderson** [comment]
Pieces of data to record:
* List of currently learnt letters
* Number of errors (per letter)
* Learning type (error in each mode)

NOTE: This is just for the user and doesnt include any backend work
