### ISSUE TITLE
Audio cue at the right time 

### ISSUE THREAD

**Issue by willwade** [AceCentre/morse-learn#8]
If you do the morse-learn with your eyes shut you fnd a few problems. For example get a letter wrong and the audio says the letter again - but no cue of the morse sound. If you had your eyes open - it does shown the image. So we need to replicate this; If letter is wrong - it needs to at a minimum sound the soundalike sound.

**Comment by sylvansson** [comment]
Hi @willwade, can you assign this to me? I'll take care of it over the weekend.

**Comment by willwade** [comment]
Awesome. Thanks.

**Comment by sylvansson** [comment]
Just to be sure, you want to hear these sounds (in order) after every failed attempt:

1. The letter ("T");
2. The Morse sound ("—");
3. The sound-alike ("tall").

?

**Comment by willwade** [comment]
Yeah. That sounds right to me. I do wonder though if “t” and then the morse sound or mnemonic should happen after each failed attempt. So
T
T, morse
T, mnemonic 

Yeah. I think that’s right. See if you do it visually The Keyer t is always shown so this way it would match it. What do you think?

**Comment by sylvansson** [comment]
I'm sorry, I'm not sure I follow. Is this what you mean?

- Before the first attempt: every sound, in this order: https://github.com/AceCentre/morse-learn/issues/8#issuecomment-626034624.
- First failed attempt: just the letter.
- Second failed attempt: the letter and the Morse sound.
- Third failed attempt: the letter and the mnemonic.
- Fourth failed attempt: same as before the first attempt.

We keep cycling through that list, starting over every four failed attempts.

Implementation-wise it would be simpler to have the same behaviour every single time, but I don't know if that's good from a usability perspective.

**Comment by sylvansson** [comment]
Just describe what you want like I'm a 5-year-old :-)

**Comment by willwade** [comment]
Right - that took me a while to get my head around this. In short - yes - your last comment is the right way. This is all to do with the idea of faded cues. You slowly give more and more cues to help someone achieve their goal. (The opposite is you get less and less.. but we do that too in this game). 

If you think your last logic is too tricky to implement I would say just add the morse sound - alongside the soundalike. That way we match the visual mode where the morse visual is given with the morse visual mneomic. That make any better sense?!

**Comment by sylvansson** [comment]
Got it. I'll implement exactly what I wrote in my last comment. Thanks!

**Comment by sylvansson** [comment]
Hi @willwade, sorry for the delay. I'll try to wrap this up this weekend!

**Comment by willwade** [comment]
Thanks! And no need for an apology!
